### ISSUE TITLE
Problem in training

### ISSUE THREAD

**Issue by rhavifbudiman** [gregorLen/AnfisTensorflow2.0#1]
i have stock data and try to predict it with anfis, and I got problem in InvalidArgumentError: slice index 15 of dimension 0 out of bounds.	 [[{{node ruleLayer_2/strided_slice_15}}]] when fit the model, I have 900 row with 1 column for data training and 96 with 1 column in data test

**Comment by Mustafa-ismail-Eyi** [comment]
Hello, i was working with this repo for my task for a few days. I think, I figure out the problem. Problem is caused from 2 thing:

1-) You have to scale your features and your target into 0-1. Be sure you do that
2-) I don't know why but the batch size causes it. Decrease the batch size from 16 to 8 or less

If you don't do step 1, your learning progress something like:
loss: nan, val_loss: nan

**Comment by gregorLen** [comment]
Hi Mustafa! Thanks alot for the feedback! I will look into it!

**Comment by Metri-Co** [comment]
I was working this repo and you must match the batch number in 'param' and the batch size in split_data function
![image](https://user-images.githubusercontent.com/87657676/131875024-37f545fb-d16b-4260-9117-9f86fdb3968b.png)

I ran the code with batch size of 16 and i had no problem. Hope it works.

**Comment by feyzazeynep** [comment]
Hello, we can estimate the data we have. So how do we predict for the future?

**Comment by gregorLen** [comment]
see answer in https://github.com/gregorLen/AnfisTensorflow2.0/issues/5#issuecomment-922731243
