### ISSUE TITLE
Future prediction

### ISSUE THREAD

**Issue by feyzazeynep** [gregorLen/AnfisTensorflow2.0#5]
We can predict the data we have. So how do we predict for the future?

**Comment by gregorLen** [comment]
**Short answer**
Simply call the trained model and insert your new data matrix as an input:

```
y_pred = fis(X_new)
```

**Why does this work?**
You can see in the initialization of the anfis class, that the underlining model is a keras model:
```
self.model = keras.Model(inputs=[input_], outputs=[L5], name = name)
```

So you are able to use all the related object methods, such as: `fis.model.predict(X)`

Or, since i've implemented this whenever the model is called

```
def __call__(self, X):
      return self.model.predict(X)
```
you can simply call the model and include the input as shown above.

Hope this helps! Cheers!

**Comment by s-krugolet** [comment]
Hi Gregor. I ran into error trying to make prediction on Mackey-Glass time series. 
I ran a code from examples and got:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-c4f5faf6ff99> in <module>()
     27 fis.model.summary()
     28 
---> 29 y_pred = fis(X)
     30 
     31 # f, axs = plt.subplots(2,1,figsize=(8,10))

2 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1572, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "defuzzLayer" (type DefuzzyLayer).
    
    in user code:
    
        File "<ipython-input-16-5fe3aebfbcaa>", line 33, in call  *
            print(tf.multiply(w_norm, a + self.CP_bias))
    
        ValueError: Dimensions must be equal, but are 16 and 32 for '{{node myanfis/defuzzLayer/Mul}} = Mul[T=DT_FLOAT](myanfis/normLayer/truediv, myanfis/defuzzLayer/add)' with input shapes: [16,25], [32,25].
    
    
    Call arguments received:
      • w_norm=tf.Tensor(shape=(16, 25), dtype=float32)
      • Xs=tf.Tensor(shape=(32, 2), dtype=float32)

Cold you please help to solve that issue.
My Colab [here](https://colab.research.google.com/gist/s-krugolet/273bbeb58473e0114600085e35ebb301/evolutionary_fuzzy_nn.ipynb)
