### ISSUE TITLE
Fit Problem

### ISSUE THREAD

**Issue by hetezadi** [gregorLen/AnfisTensorflow2.0#8]
Dear Gregor,

I hope this email finds you well, first of all, thank you so much for sharing your code on GitHub. I have a problem working with it. I have 3 inputs and 1 output, and it gives the below error:

`[/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

Incompatible shapes: [16,1] vs. [15,1]`

I found that 16 is my batch size and when I change it, this number changes.

(I found a solution and the solution is batch_size=1)  which is SGD

Thank you in advance

Kind regards

Hamed

**Comment by gregorLen** [comment]
Hi @hetezadi! Many thanks for your comment. I am not sure if I 100% understand the issue but I worked on the repo and fixed a different issue. 

Could you pull the new version of the repo, update the new package versions, and let me know if the error still pops up? If it does, I would need some more information. 

Cheers!

**Comment by hetezadi** [comment]
Hi@gregorlen

Thank you so much for the new version

In the previous version, I found that when we choose batch_size=1 (SGD) your codes work!

Again thanks

Cheers!
